/* tslint:disable */
/* eslint-disable */
/**
 * Blog - for Svelte Course
 * Svelte Blog
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ImageControllerCreateRequest {
    body: object;
}

export interface ImageControllerFindOneRequest {
    id: string;
}

export interface ImageControllerRemoveRequest {
    id: string;
}

export interface ImageControllerUpdateRequest {
    id: string;
    body: object;
}

/**
 * 
 */
export class ImageApi extends runtime.BaseAPI {

    /**
     */
    async imageControllerCreateRaw(requestParameters: ImageControllerCreateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling imageControllerCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/images`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async imageControllerCreate(requestParameters: ImageControllerCreateRequest, initOverrides?: RequestInit): Promise<object> {
        const response = await this.imageControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async imageControllerFindAllRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/images`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async imageControllerFindAll(initOverrides?: RequestInit): Promise<string> {
        const response = await this.imageControllerFindAllRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async imageControllerFindOneRaw(requestParameters: ImageControllerFindOneRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling imageControllerFindOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/images/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async imageControllerFindOne(requestParameters: ImageControllerFindOneRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.imageControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async imageControllerRemoveRaw(requestParameters: ImageControllerRemoveRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling imageControllerRemove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/images/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async imageControllerRemove(requestParameters: ImageControllerRemoveRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.imageControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async imageControllerUpdateRaw(requestParameters: ImageControllerUpdateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling imageControllerUpdate.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling imageControllerUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/images/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async imageControllerUpdate(requestParameters: ImageControllerUpdateRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.imageControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
