/* tslint:disable */
/* eslint-disable */
/**
 * Blog - for Svelte Course
 * Svelte Blog
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CategoryImageDto,
    CategoryImageDtoFromJSON,
    CategoryImageDtoFromJSONTyped,
    CategoryImageDtoToJSON,
    PostListDto,
    PostListDtoFromJSON,
    PostListDtoFromJSONTyped,
    PostListDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CategoryDetailDto
 */
export interface CategoryDetailDto {
    /**
     * 
     * @type {string}
     * @memberof CategoryDetailDto
     */
    name: string;
    /**
     * 
     * @type {CategoryImageDto}
     * @memberof CategoryDetailDto
     */
    image: CategoryImageDto;
    /**
     * 
     * @type {Array<PostListDto>}
     * @memberof CategoryDetailDto
     */
    posts: Array<PostListDto>;
}

export function CategoryDetailDtoFromJSON(json: any): CategoryDetailDto {
    return CategoryDetailDtoFromJSONTyped(json, false);
}

export function CategoryDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDetailDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': CategoryImageDtoFromJSON(json['image']),
        'posts': ((json['posts'] as Array<any>).map(PostListDtoFromJSON)),
    };
}

export function CategoryDetailDtoToJSON(value?: CategoryDetailDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'image': CategoryImageDtoToJSON(value.image),
        'posts': ((value.posts as Array<any>).map(PostListDtoToJSON)),
    };
}

