/* tslint:disable */
/* eslint-disable */
/**
 * Blog - for Svelte Course
 * Svelte Blog
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CategoryImageDto,
    CategoryImageDtoFromJSON,
    CategoryImageDtoFromJSONTyped,
    CategoryImageDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CategoryDto
 */
export interface CategoryDto {
    /**
     * 
     * @type {number}
     * @memberof CategoryDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    description: string;
    /**
     * 
     * @type {CategoryImageDto}
     * @memberof CategoryDto
     */
    image: CategoryImageDto;
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    authorFirstName: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    authorLastName: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    authorFullName: string;
}

export function CategoryDtoFromJSON(json: any): CategoryDto {
    return CategoryDtoFromJSONTyped(json, false);
}

export function CategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'image': CategoryImageDtoFromJSON(json['image']),
        'authorFirstName': json['authorFirstName'],
        'authorLastName': json['authorLastName'],
        'authorFullName': json['authorFullName'],
    };
}

export function CategoryDtoToJSON(value?: CategoryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'image': CategoryImageDtoToJSON(value.image),
        'authorFirstName': value.authorFirstName,
        'authorLastName': value.authorLastName,
        'authorFullName': value.authorFullName,
    };
}

