/* tslint:disable */
/* eslint-disable */
/**
 * Blog - for Svelte Course
 * Svelte Blog
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryImageDto
 */
export interface CategoryImageDto {
    /**
     * 
     * @type {string}
     * @memberof CategoryImageDto
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryImageDto
     */
    mimeType: string;
}

export function CategoryImageDtoFromJSON(json: any): CategoryImageDto {
    return CategoryImageDtoFromJSONTyped(json, false);
}

export function CategoryImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryImageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': json['path'],
        'mimeType': json['mimeType'],
    };
}

export function CategoryImageDtoToJSON(value?: CategoryImageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'mimeType': value.mimeType,
    };
}

