/* tslint:disable */
/* eslint-disable */
/**
 * Blog - for Svelte Course
 * Svelte Blog
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    mimeType: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    path: string;
    /**
     * 
     * @type {object}
     * @memberof Image
     */
    category: object;
    /**
     * 
     * @type {object}
     * @memberof Image
     */
    post: object;
    /**
     * 
     * @type {User}
     * @memberof Image
     */
    user: User;
}

export function ImageFromJSON(json: any): Image {
    return ImageFromJSONTyped(json, false);
}

export function ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Image {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'mimeType': json['mimeType'],
        'path': json['path'],
        'category': json['category'],
        'post': json['post'],
        'user': UserFromJSON(json['user']),
    };
}

export function ImageToJSON(value?: Image | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'mimeType': value.mimeType,
        'path': value.path,
        'category': value.category,
        'post': value.post,
        'user': UserToJSON(value.user),
    };
}

