/* tslint:disable */
/* eslint-disable */
/**
 * Blog - for Svelte Course
 * Svelte Blog
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CategoryImageDto,
    CategoryImageDtoFromJSON,
    CategoryImageDtoFromJSONTyped,
    CategoryImageDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface PostListDto
 */
export interface PostListDto {
    /**
     * 
     * @type {number}
     * @memberof PostListDto
     */
    viewCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof PostListDto
     */
    viewedByMe: boolean;
    /**
     * 
     * @type {number}
     * @memberof PostListDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PostListDto
     */
    teaser: string;
    /**
     * 
     * @type {string}
     * @memberof PostListDto
     */
    title: string;
    /**
     * 
     * @type {CategoryImageDto}
     * @memberof PostListDto
     */
    image: CategoryImageDto;
}

export function PostListDtoFromJSON(json: any): PostListDto {
    return PostListDtoFromJSONTyped(json, false);
}

export function PostListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostListDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'viewCount': json['viewCount'],
        'viewedByMe': json['viewedByMe'],
        'id': json['id'],
        'teaser': json['teaser'],
        'title': json['title'],
        'image': CategoryImageDtoFromJSON(json['image']),
    };
}

export function PostListDtoToJSON(value?: PostListDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'viewCount': value.viewCount,
        'viewedByMe': value.viewedByMe,
        'id': value.id,
        'teaser': value.teaser,
        'title': value.title,
        'image': CategoryImageDtoToJSON(value.image),
    };
}

