/* tslint:disable */
/* eslint-disable */
/**
 * Blog - for Svelte Course
 * Svelte Blog
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterResponseDto
 */
export interface RegisterResponseDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    streetNr: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    zip: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseDto
     */
    country: string;
}

export function RegisterResponseDtoFromJSON(json: any): RegisterResponseDto {
    return RegisterResponseDtoFromJSONTyped(json, false);
}

export function RegisterResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'email': json['email'],
        'username': json['username'],
        'lastName': json['lastName'],
        'street': json['street'],
        'streetNr': json['streetNr'],
        'zip': json['zip'],
        'city': json['city'],
        'country': json['country'],
    };
}

export function RegisterResponseDtoToJSON(value?: RegisterResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'email': value.email,
        'username': value.username,
        'lastName': value.lastName,
        'street': value.street,
        'streetNr': value.streetNr,
        'zip': value.zip,
        'city': value.city,
        'country': value.country,
    };
}

