/* tslint:disable */
/* eslint-disable */
/**
 * Blog - for Svelte Course
 * Svelte Blog
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterRequestDto
 */
export interface RegisterRequestDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    streetNr: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    zip: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDto
     */
    country: string;
}

export function RegisterRequestDtoFromJSON(json: any): RegisterRequestDto {
    return RegisterRequestDtoFromJSONTyped(json, false);
}

export function RegisterRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'firstName': json['firstName'],
        'username': json['username'],
        'lastName': json['lastName'],
        'street': json['street'],
        'streetNr': json['streetNr'],
        'zip': json['zip'],
        'city': json['city'],
        'country': json['country'],
    };
}

export function RegisterRequestDtoToJSON(value?: RegisterRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'firstName': value.firstName,
        'username': value.username,
        'lastName': value.lastName,
        'street': value.street,
        'streetNr': value.streetNr,
        'zip': value.zip,
        'city': value.city,
        'country': value.country,
    };
}

